defaults:
  - data: pems
  - task: forecasting
  - hydra: default
  # Allow the model to overwrite the settings below
  - _self_
  - model: diffstg

# seed: ~
eval_testset: True

wandb:
  project: "Master-Thesis"
  group: "explore"
  name: "DiffSTG_Reproduce_Results"

hydra:
  job:
    name: ${wandb.group}

trainer:
  accelerator: gpu
  devices: 1
  max_epochs: 300
  log_every_n_steps: 1

early_stopping: 5

training_hparams:
  learning_rate: 0.0001
  weight_decay: 0.00001
  # Not used yet but will configure it soon
  optimizer: Adam

  lr_scheduler:
    name: ReduceLROnPlateau
    mode: min
    factor: 0.5
    patience: 5
    monitor: val/mse

checkpointing:
  dirpath: /nfs/homedirs/sakalyan/code/thesis/outputs/checkpoints
  filename: best_model
  mode: min
  monitor: val/mse
  save_last: True
  save_top_k: 1